# Generated by Django 6.0.7 on 2026-07-25 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_wpm', models.PositiveIntegerField(default=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.FloatField(default=0.0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('content_markdown', models.TextField(blank=True, default='')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('wpm_override', models.PositiveIntegerField(blank=True, null=True)),
                ('anchor_offset_seconds', models.FloatField(default=0.0)),
                ('color_tag', models.CharField(blank=True, default='', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anchor_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anchored_children', to='api.block')),
            ],
            options={
                'ordering': ['start_seconds', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BlockResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.block')),
            ],
        ),
        migrations.CreateModel(
            name='BlockTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.block')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('blocks', models.ManyToManyField(related_name='resources', through='api.BlockResource', to='api.block')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.project')),
            ],
        ),
        migrations.AddField(
            model_name='blockresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resource'),
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=16)),
                ('target_length_min', models.FloatField(blank=True, null=True)),
                ('wpm_override', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('blocks', models.ManyToManyField(related_name='tags', through='api.BlockTag', to='api.block')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.project')),
            ],
        ),
        migrations.AddField(
            model_name='blocktag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('voiceover', 'Voiceover'), ('broll', 'B-Roll'), ('tags', 'Tags'), ('resources', 'Resources')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.script')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='block',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.track'),
        ),
        migrations.AddConstraint(
            model_name='blockresource',
            constraint=models.UniqueConstraint(fields=('block', 'resource'), name='unique_block_resource'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('project', 'label'), name='unique_tag_label_per_project'),
        ),
        migrations.AddConstraint(
            model_name='blocktag',
            constraint=models.UniqueConstraint(fields=('block', 'tag'), name='unique_block_tag'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('script', 'kind'), name='unique_track_kind_per_script'),
        ),
    ]
