# Generated by Django 6.0.7 on 2026-07-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='track',
            name='unique_track_kind_per_script',
        ),
        migrations.AddField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='track',
            name='color',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='track',
            name='is_script_track',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='kind',
            field=models.CharField(max_length=64),
        ),
    ]
