# Generated by Django 6.0.7 on 2026-07-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_track_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='clip_kind',
            field=models.CharField(blank=True, choices=[('muted', 'Muted Background Clip'), ('clip', 'Clip'), ('full', 'Full Clip')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='block',
            name='editor_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='block',
            name='source_in_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='source_out_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
